# Following https://dzfrias.dev/blog/deploy-rust-cross-platform-github-actions/
name: Deploy

on:
  push:
    tags:
      # Regex for a version number such as 0.2.1
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  
env:
  CARGO_TERM_COLOR: always

jobs:

  build-and-upload:   
    name: Build and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            
          #- build: macos
          #  os: macos-latest
          #  target: x86_64-apple-darwin

          #- build: windows-gnu
          #  os: windows-latest
          #  target: x86_64-pc-windows-gnu
    
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Get the release version from the tag
      shell: bash
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Build
      run: cargo build --verbose --release
    - name: Build archive
      shell: bash
      run: |
        # Replace with the name of your binary
        binary_name="ansys-stress-propagation"
        dirname="$binary_name-${{ env.VERSION }}-${{ matrix.target }}"
        mkdir "$dirname"
        mv "target/release/$binary_name" "$dirname"
        tar -czf "$dirname.tar.gz" "$dirname"
        echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
    - name: Upload the binaries
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ env.ASSET }}
